install-dev: build
  install -D libtree-sitter-orgncf.so ~/.local/share/nvim/site/parser/orgncf.so
  mkdir -p ~/.local/share/nvim/site/queries/orgncf
  cp -r queries/* ~/.local/share/nvim/site/queries/orgncf/
  nvim ../netconfig.ncf -c 'InspectTree'

build:
  tree-sitter generate
  make

install-nvim:
  make
  install -D libtree-sitter-orgncf.so ~/.local/share/nvim/site/parser/orgncf.so
  install -D queries/highlights.scm ~/.local/share/nvim/site/queries/orgncf/highlights.scm
  #mkdir -p ~/.config/nvim/ftplugin && echo 'vim.treesitter.start()' > ~/.config/nvim/ftplugin/orgncf.lua
  #mkdir -p ~/.config/nvim/ftdetect && echo 'vim.filetype.add({ extension = { ncf = "orgncf", }, })' > ~/.config/nvim/ftdetect/orgncf.lua

